import type { Anchor } from '@/lib/perceptual-dial/types';

export const TIME_OF_DAY_ANCHORS: Anchor[] = [
  {
    id: 'dawn',
    label: 'Dawn',
    position: [0.10],
    params: {
      'kelvin.kelvin':     3200,
      'light.exposure':     -0.3,
      'light.contrast':     -8,
      'light.highlights':  -15,
      'light.shadows':     +20,
      'color.vibrance':     +5,
      'hsl.orange_sat':    +10,
      'hsl.blue_sat':      +15,
      'filters.vignette_amount': -10,
    },
  },
  {
    id: 'noon',
    label: 'Noon',
    position: [0.30],
    params: {
      'kelvin.kelvin':     5500,
      'light.exposure':      0,
      'light.contrast':    +10,
      'light.highlights':    0,
      'light.shadows':       0,
      'color.vibrance':      0,
      'hsl.orange_sat':      0,
      'hsl.blue_sat':      +15,
      'filters.vignette_amount': 0,
    },
  },
  {
    id: 'golden',
    label: 'Golden',
    position: [0.55],
    params: {
      'kelvin.kelvin':     3400,
      'light.exposure':     +0.2,
      'light.contrast':     +5,
      'light.highlights':  -20,
      'light.shadows':     +10,
      'color.vibrance':    +12,
      'hsl.orange_sat':    +25,
      'hsl.blue_sat':       -5,
      'filters.vignette_amount': -8,
    },
  },
  {
    id: 'blue',
    label: 'Blue',
    position: [0.80],
    params: {
      'kelvin.kelvin':     8500,
      'light.exposure':     -0.5,
      'light.contrast':    +15,
      'light.highlights':  -10,
      'light.shadows':      +5,
      'color.vibrance':     +5,
      'hsl.orange_sat':    -25,
      'hsl.blue_sat':      +20,
      'filters.vignette_amount': -15,
    },
  },
  {
    id: 'night',
    label: 'Night',
    position: [1.00],
    params: {
      'kelvin.kelvin':     4200,
      'light.exposure':     -1.2,
      'light.contrast':    +25,
      'light.highlights':  -40,
      'light.shadows':     -10,
      'color.vibrance':     +8,
      'hsl.orange_sat':    -10,
      'hsl.blue_sat':      +15,
      'filters.vignette_amount': -30,
    },
  },
];
