/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EditorSharedTypes =
  | Widget
  | Scope
  | ControlBinding
  | SessionStateSnapshot
  | StateEvent
  | ImageContext
  | EnrichedImageContext
  | OperationGraph;
/**
 * Discriminated union over all control_type schemas.
 */
export type ControlSchema =
  | SliderSchema
  | NumericPairSchema
  | ToggleSchema
  | ChoiceSchema
  | ColorSchema
  | CurveSchema
  | CurvePointSchema
  | MaskThumbnailSchema
  | RegionPickerSchema
  | BeforeAfterToggleSchema
  | HistogramMarkerSchema
  | TextSchema
  | SwatchSchema
  | HueWheelSchema
  | CurveEditorSchema
  | PointListSchema
  | EnumSelectSchema
  | BoolToggleSchema
  | KelvinStripSchema
  | TintStripSchema;
/**
 * Discriminated union over the scope kinds.
 */
export type Scope = GlobalScope | NamedRegionScope | MaskScope | ImageNodeScope;

export interface Widget {
  bindings: ControlBinding[];
  category: string | null;
  composed: boolean;
  createdAt: string;
  dismissedAtRevision: number | null;
  displayName: string | null;
  id: string;
  intent: string;
  lockedParams: string[];
  nodes: WidgetNode[];
  opId: string | null;
  origin: WidgetOrigin;
  preview: WidgetPreview;
  reasoning: string | null;
  rejectedAttempts: ResolvedNumbers[];
  revision: number;
  scope: Scope;
  status: "active" | "dismissed" | "accepted";
  updatedAt: string;
}
export interface ControlBinding {
  controlSchema: ControlSchema;
  controlType:
    | "slider"
    | "numeric_pair"
    | "toggle"
    | "choice"
    | "color"
    | "curve"
    | "curve_point"
    | "mask_thumbnail"
    | "region_picker"
    | "before_after_toggle"
    | "histogram_marker"
    | "text"
    | "swatch"
    | "hue_wheel"
    | "curve_editor"
    | "point_list"
    | "enum_select"
    | "bool_toggle"
    | "kelvin_strip"
    | "tint_strip";
  default:
    | number
    | string
    | boolean
    | unknown[]
    | {
        [k: string]: unknown;
      };
  label: string;
  paramKey: string;
  reasoning: string | null;
  target: NodeParamTarget;
  value:
    | number
    | string
    | boolean
    | unknown[]
    | {
        [k: string]: unknown;
      };
}
export interface SliderSchema {
  controlType: "slider";
  max: number;
  min: number;
  step: number;
  unit: string;
}
export interface NumericPairSchema {
  controlType: "numeric_pair";
  labelA: string;
  labelB: string;
  maxA: number;
  maxB: number;
  minA: number;
  minB: number;
  stepA: number;
  stepB: number;
}
export interface ToggleSchema {
  controlType: "toggle";
  offLabel: string;
  onLabel: string;
}
export interface ChoiceSchema {
  allowCustom: boolean;
  controlType: "choice";
  /**
   * @minItems 1
   */
  options: [ChoiceOption, ...ChoiceOption[]];
}
export interface ChoiceOption {
  label: string;
  swatch: number[] | null;
  value: string;
}
export interface ColorSchema {
  controlType: "color";
  presets: number[][];
  showAlpha: boolean;
  space: "rgb" | "lab" | "hsl";
}
export interface CurveSchema {
  channel: ("luma" | "r" | "g" | "b") | null;
  controlType: "curve";
  maxPoints: number;
  minPoints: number;
}
export interface CurvePointSchema {
  channel: "luma" | "r" | "g" | "b";
  controlType: "curve_point";
  xMax: number;
  xMin: number;
  yMax: number;
  yMin: number;
}
export interface MaskThumbnailSchema {
  allowCombine: ("union" | "intersect" | "subtract")[];
  allowReplace: boolean;
  controlType: "mask_thumbnail";
}
export interface RegionPickerSchema {
  allowActiveSelection: boolean;
  allowGlobal: boolean;
  candidateLabels: string[];
  controlType: "region_picker";
}
export interface BeforeAfterToggleSchema {
  controlType: "before_after_toggle";
  splitOrientation: "horizontal" | "vertical" | "swap";
}
export interface HistogramMarkerSchema {
  channel: "luma" | "r" | "g" | "b";
  controlType: "histogram_marker";
  markerKind: "black_point" | "white_point" | "gamma";
}
export interface TextSchema {
  controlType: "text";
  maxLen: number;
  placeholder: string;
}
/**
 * Colour swatch picker — mirrors ColorSchema but uses registry vocab.
 */
export interface SwatchSchema {
  controlType: "swatch";
  presets: number[][];
  showAlpha: boolean;
  space: "rgb" | "lab" | "hsl";
}
/**
 * Hue wheel — degree range [min, max].
 */
export interface HueWheelSchema {
  controlType: "hue_wheel";
  max: number;
  min: number;
}
/**
 * Full curve editor — mirrors CurveSchema but uses registry vocab.
 */
export interface CurveEditorSchema {
  channel: ("luma" | "r" | "g" | "b") | null;
  controlType: "curve_editor";
  maxPoints: number;
  minPoints: number;
}
/**
 * Editable list of curve/spline points (debug / advanced editor).
 */
export interface PointListSchema {
  controlType: "point_list";
  maxPoints: number;
  minPoints: number;
}
/**
 * Drop-down / segmented enum selector — mirrors ChoiceSchema.
 */
export interface EnumSelectSchema {
  allowCustom: boolean;
  controlType: "enum_select";
  /**
   * @minItems 1
   */
  options: [ChoiceOption, ...ChoiceOption[]];
}
/**
 * Boolean toggle — mirrors ToggleSchema.
 */
export interface BoolToggleSchema {
  controlType: "bool_toggle";
  offLabel: string;
  onLabel: string;
}
/**
 * Kelvin temperature strip — same fields as SliderSchema.
 */
export interface KelvinStripSchema {
  controlType: "kelvin_strip";
  max: number;
  min: number;
  step: number;
  unit: string;
}
/**
 * Green↔magenta tint strip — same fields as SliderSchema, painted with a
 * teal-to-magenta gradient track on the frontend. Paired with kelvin_strip
 * on white-balance ops.
 */
export interface TintStripSchema {
  controlType: "tint_strip";
  max: number;
  min: number;
  step: number;
  unit: string | null;
}
export interface NodeParamTarget {
  nodeId: string;
  paramKey: string;
}
export interface WidgetNode {
  id: string;
  inputs: string[];
  layerId: string;
  layerIds: string[] | null;
  opId: string | null;
  params: {
    [k: string]:
      | number
      | string
      | boolean
      | unknown[]
      | {
          [k: string]: unknown;
        };
  };
  scope: Scope;
  type: string;
  widgetId: string;
}
export interface GlobalScope {
  kind: "global";
}
export interface NamedRegionScope {
  kind: "named_region";
  label: string;
}
export interface MaskScope {
  kind: "mask";
  maskId: string;
}
export interface ImageNodeScope {
  imageNodeId: string;
  kind: "image_node";
  layerIds: string[];
}
export interface WidgetOrigin {
  anchor: string | null;
  kind:
    | "mcp_user_prompt"
    | "mcp_autonomous"
    | "user_palette"
    | "fused_expansion"
    | "refine"
    | "repeat"
    | "tool_invoked";
  parentWidgetId: string | null;
  prompt: string | null;
}
export interface WidgetPreview {
  autoBeforeAfter: boolean;
  kind: "thumbnail" | "histogram_delta" | "color_swatches" | "none";
}
/**
 * One attempt's tunable values + optional reasoning. Used both by the
 * fused-tool framework (Plan 2) and by Widget.rejected_attempts for the
 * repeat-widget anchor log.
 */
export interface ResolvedNumbers {
  reasoning: string | null;
  values: {
    [k: string]:
      | number
      | string
      | boolean
      | unknown[]
      | {
          [k: string]: unknown;
        };
  };
}
export interface SessionStateSnapshot {
  aiAccess: boolean;
  imageContext: EnrichedImageContext | null;
  masksIndex: {
    [k: string]: unknown;
  }[];
  operationGraph: OperationGraph;
  revision: number;
  sessionId: string;
  widgets: Widget[];
}
/**
 * Additive extension of v1 ImageContext.
 *
 * Cheap pass fills the numeric fields locally; the Claude-augmented pass
 * fills `estimated_white_point`, `wb_neutral_confidence`, `grade_character`,
 * `problems`, plus per-region `is_skin_likely` / `is_sky_likely`.
 */
export interface EnrichedImageContext {
  candidateRegions: CandidateRegion[];
  /**
   * @minItems 2
   * @maxItems 2
   */
  castDirection: [unknown, unknown];
  castStrength: number;
  clippedHighlightsPct: number;
  clippedShadowsPct: number;
  colorPalette: ColorSwatch[];
  contrastP10P90: number;
  dominantTones: ("shadows" | "midtones" | "highlights")[];
  /**
   * @minItems 3
   * @maxItems 3
   */
  estimatedWhitePoint: [unknown, unknown, unknown];
  generatedAt: string;
  gradeCharacter: string;
  lighting: "flat" | "backlit" | "side" | "rim" | "mixed";
  /**
   * @minItems 256
   * @maxItems 256
   */
  lumaHistogram: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ];
  medianLuma: number;
  modelName: string;
  modelVersion: string;
  mood: string;
  problems: Problem[];
  regionStats: RegionStats[];
  rgbHistograms: {
    [k: string]: number[];
  };
  subjects: string[];
  wbNeutralConfidence: number;
}
export interface CandidateRegion {
  bbox: [number, number, number, number] | null;
  description: string;
  label: string;
  maskPngBase64: string | null;
  paths: number[][][] | null;
  representativePoint: [number, number] | null;
}
export interface ColorSwatch {
  /**
   * @minItems 3
   * @maxItems 3
   */
  rgb: [unknown, unknown, unknown];
  weight: number;
}
export interface Problem {
  bbox: [number, number, number, number] | null;
  kind:
    | "clipped_highlights"
    | "crushed_shadows"
    | "low_contrast"
    | "strong_color_cast"
    | "noisy_shadows"
    | "uneven_white_balance";
  regionLabel: string | null;
  severity: number;
  suggestedFusedTools: string[];
}
export interface RegionStats {
  contrastP10P90: number;
  dominantSwatches: ColorSwatch[];
  isSkinLikely: boolean;
  isSkyLikely: boolean;
  label: string;
  /**
   * @minItems 32
   * @maxItems 32
   */
  lumaHistogram: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ];
  meanLuma: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  meanRgb: [unknown, unknown, unknown];
  pixelCount: number;
  saturationMean: number;
}
export interface OperationGraph {
  id: string;
  metadata: {
    [k: string]: string;
  };
  nodes: Node[];
  panelBindings: PanelBinding[];
  reasoning: string | null;
  userGoal: string;
}
export interface Node {
  id: string;
  inputs: string[];
  layerId: string;
  layerIds: string[] | null;
  params: {
    [k: string]:
      | number
      | string
      | boolean
      | unknown[]
      | {
          [k: string]: unknown;
        };
  };
  scope: Scope1;
  type: string;
  widgetId: string | null;
}
export interface Scope1 {
  confidence: number | null;
  kind: "global" | "mask:click" | "mask:proposed";
  label: string | null;
  point: [unknown, unknown] | null;
}
export interface PanelBinding {
  control: "slider" | "toggle" | "picker";
  default: number | string | boolean | null;
  label: string;
  max: number | null;
  min: number | null;
  nodeId: string;
  paramKey: string;
  reasoning: string | null;
  step: number | null;
}
export interface StateEvent {
  emittedAt: string;
  kind:
    | "widget.created"
    | "widget.updated"
    | "widget.deleted"
    | "widget.accepted"
    | "widget.restored"
    | "mask.created"
    | "mask.deleted"
    | "mask.renamed"
    | "selection.changed"
    | "context.updated"
    | "dismissal.added"
    | "note.created"
    | "phase.started"
    | "phase.progress"
    | "phase.completed"
    | "phase.cancelled"
    | "canonical.updated"
    | "image_node_transform.updated"
    | "mcp.usage"
    | "history.applied"
    | "state.gap"
    | "session.ai_access";
  payload: {
    [k: string]: unknown;
  };
  revision: number;
}
export interface ImageContext {
  candidateRegions: CandidateRegion[];
  dominantTones: ("shadows" | "midtones" | "highlights")[];
  generatedAt: string;
  lighting: "flat" | "backlit" | "side" | "rim" | "mixed";
  modelName: string;
  modelVersion: string;
  mood: string;
  subjects: string[];
}
